### ISSUE TITLE
`ARCH_PTR_BYTES` can be extracted from the SVD-file

### ISSUE THREAD

**Issue by RHamalainen** [soc-hub-fi/keelhaul#15]
Address pointer bit count is expressed in the SVD-file inside `size`-element.

**Comment by hegza** [comment]
It cannot be extracted from the SVD file.

To my knowledge, the number of bits used to represent addresses on a given platform is a CPU dependent quantity which is not available in CMSIS-SVD. CMSIS-SVD describes the following fields, none of which is the number of bits used to represent addresses:

- /device/size/ - the default bit-width for register values
- /device/addressUnitBits/ - the number of bits uniquely selected by each address (usually 8)
- /device/width/ - maximum data transfer supported by bus infrastructure. This is close to the data type used to represent addresses and might concide with it on most platforms. However, I believe they are distinct.

Can I close this?

**Comment by hegza** [comment]
By the way, one nice thing about the address width is that **the compiler** does know it, and we should always be able to reference it in generated code using `usize`. I.e., things running on SysCtrl are guaranteed to run on an `riscv32imc` using 32-bit address width (`usize`), while things running on HPC would use the `riscv64imac`/`gc`, using 64-bit address width (also `usize`).

The implication is that most of the codegen code that currently depends on the `ArchSize` might not actually require it.

**Comment by RHamalainen** [comment]
>The number of bits used to represent single address is not available in CMSIS-SVD.

True, I'll close this.
